version: '3'

services:

### Application Containers ###################################

  web:
    image: owendland/nginx-php-laravel:1.0
    ports:
      - 80:80
    volumes:
      - ./:/var/www/code
    depends_on:
      - redis
      - mysql

  worker:
    image: laradock/workspace:1.9-71
    command: "php artisan horizon"
    working_dir: /var/www/code
    volumes:
      - ./:/var/www/code
    depends_on:
      - redis
      - mysql

  cli:
    image: laradock/workspace:1.9-71
    tty: true
    working_dir: /var/www/code
    volumes:
      - ./:/var/www/code
    depends_on:
      - redis
      - mysql

  artifact:
    image: gcr.io/horizon-demo-185900/lara-sqrrl-resizer
    build:
      context: .

### Cache Container #########################################

  redis:
    image: redis:4.0.2
    ports:
      - 6379:6379

### MySQL Container ##########################################

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horizon
      MYSQL_USER: jdoe
      MYSQL_PASSWORD: secret
    volumes:
      - ./build/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306