version: '3'

services:

### Application Containers ###################################

  web:
    image: gcr.io/horizon-demo-185900/nginx-php
    build:
      context: .
      dockerfile: build/docker/nginx-php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/code
    depends_on:
      - redis

  worker:
    image: laradock/workspace:1.9-71
    command: "php artisan horizon"
    working_dir: /var/www/code
    volumes:
      - ./:/var/www/code
    depends_on:
      - redis

  cli:
    image: laradock/workspace:1.9-71
    tty: true
    working_dir: /var/www/code
    volumes:
      - ./:/var/www/code
    depends_on:
      - redis

  artifact:
    image: gcr.io/horizon-demo-185900/horizon-demo-app
    build:
      context: .
      dockerfile: build/docker/artifact/Dockerfile

### Cache Container #########################################

  redis:
    image: redis:4.0.2
    ports:
      - 6379:6379